const array1=["Ana",2,"Javi",5,"Roberto",7,"Vanessa",10];

function deletenum(array1){
  return  $array1=array1.filter(num => typeof(num)=== typeof(num[1]));
  }

  
function par(x){
    return x%2 == 0 //|| array1.filter(num => typeof(num)=== typeof(num[1]));
    }

let pararray=array1.filter(par);
console.log(pararray,(deletenum(array1)));


//console.log(deletenum(array1))





// let aca=deletenum(array1);
// return array1= array1.map(parseInt);


/*function power2(x){
    return x**2;
    }
    let array = [1,2,3,4,5];
    let newArray = array.map(power2);
    console.log(newArray); */

    
// console.log(cars_names);


// console.log(aca);

